version: '3.4'

services:
  feedsvc:
    build:
      dockerfile: feedService.Dockerfile
      context: .
    ports:
      - 8080:8080
    image: friendbookfeedservice
    environment:
      - POST_SERVICE_URL = http://postssvc:8080